### ISSUE TITLE
Bug: head cleaning does not turn the motor on

### ISSUE THREAD

**Issue by philpem** [keirf/Greaseweazle#101]
`gw clean` does not turn the motor on when cleaning the heads.  (`gw read` works fine)

This causes issues --  some drives won't allow the head to be stepped when the motor isn't running. The more serious issue is that the head can dig into some types of cleaning disc and damage or tear them if it is "scrubbed" with the disc stationary...

```
Host Tools: v0.26
Greaseweazle:
  Device:   /dev/ttyACM0
  Model:    F7 Lightning Plus
  Firmware: v0.26
  Serial:   (redacted)
  USB Rate: High Speed (480 Mbit/s)
```

**Comment by keirf** [comment]
It definitely does turn the motor on, just tested it myself with a normal floppy disk. Perhaps the drive isn't recognising a disk is inserted?

**Comment by philpem** [comment]
I'm suspecting this might be related to the specific drive. I've just re-tested with another drive and things worked as expected. But this full-height Shugart and a Mitsubishi are giving me grief.

They do spin fine when I use a Polar floppy drive tester/exerciser to run tests -- just that the heads are filthy and inaccessible, and so I need to use a cleaning disk.

Will look into this and update the ticket if I figure anything out. The jumper settings may be a bit weird as these drives came from a BBC Micro.
