### ISSUE TITLE
Beware of 4 MHz STM32 models

### ISSUE THREAD

**Issue by nretro** [keirf/Greaseweazle#11]
I bought a STM32F103C8T6 from China on ebay. On close examination, the description says 

4-16MHz crystal.

and in fact has a 4 MHz instead of an 8 MHz crystal. The blinky test succeeds nicely, but only at half speed (output at 57600 baud).

![STM32F103C8_4MHZ](https://user-images.githubusercontent.com/49684007/69893972-05c30b00-1319-11ea-94f8-d8d5cf029bc4.jpg)

**Comment by keirf** [comment]
I figure I ought to be able to measure HSE against the HSI or LSI oscillators and then set things up correctly for 4 vs 8 mhz crystal...

**Comment by turnkit** [comment]
Is there a proper forum for non bug issues?

Will the black pill work just fine too?

https://www.cnx-software.com/2019/12/24/stm32-black-pill-board-features-stm32f4-cortex-m4-mcu-optional-spi-flash/

**Comment by keirf** [comment]
There is a Facebook group. The black pill should work but note the pin arrangement is different. The few black pills I purchased had fake stm32 which didn't work.

**Comment by cbrunschen** [comment]
I think @turnkit meant the different, new "black pill" that is based on an STM32F4x1 chip, see [the link they posted](https://www.cnx-software.com/2019/12/24/stm32-black-pill-board-features-stm32f4-cortex-m4-mcu-optional-spi-flash/), with a USB-C connector for visual differentiation if nothing else.

**Comment by keirf** [comment]
It would need porting but could then work. I didn't spot any of these new ones on ebay yet.

**Comment by cbrunschen** [comment]
It seems they're mainly available on Aliexpress (for example [1](https://www.aliexpress.com/item/4000084631884.html), [2](https://www.aliexpress.com/item/4000103610226.html), [3](https://www.aliexpress.com/item/4000138305460.html), [4](https://www.aliexpress.com/item/4000068998794.html)) at the moment.

**Comment by ptor** [comment]
If someone who has ordered a verified working one (a blue, or the new black pill) from a "cheap" source (ebay or Aliexpress) could link to where they bought it from, I would be eternally grateful. I've been on the fence for a long time since I simply don't dare buy one - it looks like it's hit or miss.

**Comment by nretro** [comment]
Just get a Greaseweazle F730 DYI Kit from Keir. He posts them for a couple of pounds. Just send him an email. Not the cheapest way, but you definitely get a working one while supporting the project.

I've also made some progress on the 4MHz problem. Due to PLL limitations, you only can get the max speed of 72MHz on the STM32, when using 6, 8 or 12 MHz crystals. But it's easy to source these crystals cheaply and replacing them should not be a problem.

**Comment by keirf** [comment]
Not much more to say here then. I haven't had any more reports of 4MHz crystals. If there are then I will consider updating the docs, or make Blinky aware of it.
