### ISSUE TITLE
linux setup wiki 

### ISSUE THREAD

**Issue by Gunstick** [keirf/Greaseweazle#111]
https://github.com/keirf/Greaseweazle/wiki/Software-Installation#linux
To avoid "Please run setup.sh from within the Greaseweazle folder"

replace 

```
Greaseweazle/scripts/setup.sh
```

with

```
cd Greaseweazle
./scripts/setup.sh
cd ..
```
The ´cd ..´ is there so the following command lines still work

**Comment by keirf** [comment]
Thanks. I changed it to so that the steps should be executed within the folder in the first place, which seems better than how it was!
