### ISSUE TITLE
0.30 Windows release doesn't contain the python.dll files.

### ISSUE THREAD

**Issue by M1kerochip** [keirf/Greaseweazle#117]
The windows .zip file doesn't contain all the files required to run gw.exe.

Just thought to let you know.

(Also, if you recall, that problem APM32F103 I had from some time back, it wouldn't update via the update command. I could only flash the .hex file manually. It now updates fine, with the 0.30 gw.exe and .upd file.)

**Comment by keirf** [comment]
Can you say specifically what it is missing?

**Comment by keirf** [comment]
Oh I think I deleted copies out of the root of the zip file rather than just under lib/. I'll fix it later thanks!

**Comment by keirf** [comment]
Should now be fixed.
