### ISSUE TITLE
Reading more than 84 tracks (0-84) or 00-85) both sides, gives me a ** FATAL ERROR: SCP: Too many tracks error, and the .scp file is blank.

### ISSUE THREAD

**Issue by M1kerochip** [keirf/greaseweazle#119]
GW -info

Host Tools: v0.30
Greaseweazle:
  Device:   COM4
  Model:    F1
  Firmware: v0.30
  Serial:   GW00500004590000174E4D4A33
  USB Rate: Full Speed (12 Mbit/s)

**Comment by M1kerochip** [comment]
Reading c=0-85:h=0-1 revs=5
T0.0: Raw Flux (476103 flux in 1063.80ms)
T0.1: Raw Flux (533763 flux in 1169.26ms)
....
T85.0: Raw Flux (191913 flux in 1093.07ms)
T85.1: Raw Flux (222714 flux in 1153.00ms)
** FATAL ERROR:
SCP: Too many tracks

From the output of reading a 1.44MB IBM PC disk, in a HD drive, bitcell read rate of 500, 5 revolutions, tracks 0-85, both sides.

**Comment by keirf** [comment]
You can only store up to track 84.1 in an SCP image. Hence the failure is correct. Should it write out what it's got? Maybe. Perhaps it should warn instead of fatal?

**Comment by M1kerochip** [comment]
Is the track limit new? I certainly used to store 86 tracks in earlier .scp images.

**Comment by keirf** [comment]
Using Greaseweazle?

**Comment by M1kerochip** [comment]
Yes. (I only have a GW! So, it wasn't something else!) I've several Atari ST images where there's data from tracks 0-83, so, I've read them using 84 and 85 tracks to make sure there's nothing beyond that.

**Comment by M1kerochip** [comment]
The only difference was they're DS DD not DS HD disks.

**Comment by keirf** [comment]
Can, for example, HxC load your old images with more tracks and you can view the disk with that many tracks?

**Comment by M1kerochip** [comment]
No, seems not! I've a note with the 85/86 tracks that they're not working, and had to create them again with 84 tracks!

Well, ok then! I guess we can close this!

But, yes, I suppose, writing out the first 84 tracks would be beneficial, or like you say, warning I guess.
It's slightly annoying to get to the end, and then find you have no disk image!

**Comment by keirf** [comment]
If you want more tracks properly supported, you might have better luck with Kryoflux streams. Worth a try anyway!

**Comment by M1kerochip** [comment]
Saving out 0-83 tracks would probably solve my initial 'problem' 😝 

But, nah, I'm good with the SPC stream 😄

Thanks again!
