### ISSUE TITLE
Support for ibm.mfm 1.2MB 5.25 floppy

### ISSUE THREAD

**Issue by xinteksik** [keirf/greaseweazle#122]
https://github.com/keirf/Greaseweazle/blob/9c71e06730926ed9fa3a3cc4eb9c51f75c99220b/scripts/greaseweazle/codec/ibm/mfm.py#L346

class IBM_MFM_1M44 is fine. But what about class IBM_MFM_1M2 with nsec=15 (18 for 1M44).

**Comment by keirf** [comment]
This is supported in latest releases.
