### ISSUE TITLE
HFE files created by reading MFM floppies are not usable

### ISSUE THREAD

**Issue by tdaede** [keirf/greaseweazle#126]
When reading a raw floppy, either 1.44MB or 1.2MB IBM format, the HFE image is corrupted somehow - disk-analyser does not find any tracks, and writing the same HFE image back to disk results in an unbootable disk. Reading to a SCP image instead, and writing that back to disk or using disk-analyser works as expected.

I can attach some reads of formatted but otherwise empty floppies in the two formats if needed.

**Comment by keirf** [comment]
Possibly auto rate should sample a track and choose something sensible.
