### ISSUE TITLE
Can't write scp files created by fluxengine: division by zero

### ISSUE THREAD

**Issue by tdaede** [keirf/greaseweazle#131]
Create a scp file in fluxengine like so:
```
./fluxengine write ibm1440 -i anything.img -d test.scp
```
Write it with greaseweazle:
```
/gw write test.scp
Writing c=0-81:h=0-1
Writing Track 0.0...** FATAL ERROR:
float division by zero
```

**Comment by keirf** [comment]
For convenience can you upload your problem scp and provide a link?

**Comment by keirf** [comment]
Scrub that, I reproduced it easily enough.

**Comment by keirf** [comment]
Ok this is due to the unique way FluxEngine produces SCP images. Every track has five revolutions, even though at most one is populated. This confuses Greaseweazle. I will have to teach it about this layout.

**Comment by tdaede** [comment]
Is that allowed by the SCP format? Another option is to change fluxengine's writer to not produce unpopulated tracks.

**Comment by keirf** [comment]
I don't think it's explicitly discounted by the SCP spec. I probably shouldn't crash on it anyway.

**Comment by davidgiven** [comment]
I'm fixing this at my end --- it's clearly wrong.

If I were to allow SCP files with more than five revolutions, would that cause any practical problems? It's essentially the one thing preventing me from using SCP as the primary file format...

**Comment by d235j** [comment]
> If I were to allow SCP files with more than five revolutions, would that cause any practical problems? It's essentially the one thing preventing me from using SCP as the primary file format...

The SCP spec is unclear on this. It says:

> BYTE 0x05 is the number of revolutions, which is how many revolutions for each track is contained in the image.

> Starting at BYTE 0x04 are three longwords for each revolution that is stored.  Typically, a maximum of five sets of three longwords are stored using the SuperCard Pro's imaging program, but this is user defined and can vary from image to image.  Using BYTE 0x05 of the main file header, you can determine the number of sets of three longwords (one for each revolution stored).  The three longwords for each entry are described below: [...]

> ; 0005              NUMBER OF REVOLUTIONS (1-5)


That said I would recommend looking into [A2R 3.0](https://applesaucefdc.com/a2r/) as a primary file format as it is way more flexible than SCP. That said, it does not support index-to-index captures, intentionally requiring an overlap of at least a quarter of a track — this is because if the data was not written index-aligned, it is impossible to reconstruct it from an index-to-index capture without some overlap.

**Comment by keirf** [comment]
I don't restrict SCP images to five revolutions maximum, and I've had no problems reported. So I would not worry about that.
