### ISSUE TITLE
SCP MFM floppy images

### ISSUE THREAD

**Issue by staticmem** [keirf/Greaseweazle#14]
Today I imaged a 3.5" HD DOS 1.44MB floppy disk with my GW.  The resultant SCP file is 74 MB in size.  I don't know about SCP disk images but I assume this is normal?

Is there some conversion tool I can use to convert the MFM floppy SCP image to say a DSK (CPCEMU) disk image or a RAW file containing only the sector data? or other disk images?

**Comment by keirf** [comment]
Yes SCP images are very large.

Use HxC software to visualise the track data and check it all looks good. You may also be able to convert to IMG and EDSK with the same tool. My own Disk-Utilities (Linux command line) can be used to convert to IMG.
