### ISSUE TITLE
Request add h[n].id= to set / sector head field to value

### ISSUE THREAD

**Issue by z80micro-mc** [keirf/greaseweazle#144]
Add h[n].id=value

eg 
      h1.id=0    force side 1 sector header head field to 0
      h0.id=0

     h0.id=1    force side 0 sector header head filed to 1

Peter

**Comment by keirf** [comment]
I want to sort this via (to be implemented) config files rather than direct on the command line.

**Comment by keirf** [comment]
Consider this done, see #261
