### ISSUE TITLE
Request add predefined type for IBM 3740 format

### ISSUE THREAD

**Issue by z80micro-mc** [keirf/greaseweazle#147]
Add new type IBM.3740 to support FM  disks:

ideally with number of sectors, sector size, no cylinders selectable.

eg standard 8" single density disk as per WD 279x chip IBM3740 track format

c=0-76:s=1-26:size=0    standard single sided IBM 3740 8" disk. 77 x 26 x 128 byte sectors

c=0-39:s=1-16:size=0    5.25" disk using  IBM 3740 type track format . 40 x 16 x 128 byte sectors

c=0-39:s=1-16:size=1    5.25" disk using  IBM 3740 type track format . 40 x 16 x 256 byte sectors

c=0-39:s=1-16:size=2    5.25" disk using  IBM 3740 type track format . 40 x 16 x 512 byte sectors

Peter

**Comment by keirf** [comment]
Consider this done, see #261
