### ISSUE TITLE
capsimage 5.2?

### ISSUE THREAD

**Issue by VorpalBlade** [keirf/greaseweazle#199]
I noticed that you specifically mention capsimage 4.2 in https://github.com/keirf/greaseweazle/wiki/IPF-Images, but it seems that a version 5.2 is available now as well, and is the version packaged by Arch Linux AUR (https://aur.archlinux.org/packages/capsimage). 

As I recently made a package for greaseweazle for Arch Linux (https://aur.archlinux.org/packages/greaseweazle), I'd like to know if I can add an optional dependency on the other package or if I need to package the older version separately for this.

I unfortunately don't have any IPF images to test this feature with, otherwise I wouldn't bother you with this question.

**Comment by keirf** [comment]
It should work fine as greaseweazle will try to load `libcapsimage.so.5`. You can find loads of IPF downloads here: http://www.oldgamesfinder.com/?m=2&q=Europe
So you can test it for yourself.
