### ISSUE TITLE
issue : bad sectors with the "convert" action

### ISSUE THREAD

**Issue by Telev78** [keirf/greaseweazle#206]
Hello,

I read some 5.25 1.2Mb floppy with this command line `gw read --drive B disk1\track00.0.raw`
I have an issue with one floppy.
When i open the file with HxCFloppyEmulator, the backup is correctly read and the track analyser don't show any bad sector.

![indy3(HxCfloppyEmulator)](https://user-images.githubusercontent.com/19438099/178105010-e2bdc9a7-9328-4d8c-bed2-109b4f1efd3d.jpg)

The export function with HxC work correctly.

But, when i use this command line : `gw convert --format ibm.1200 disk4\track00.0.raw disk4.ima`, i get many bad sector...

![image](https://user-images.githubusercontent.com/19438099/178105170-24432438-5dc6-4fd2-b035-73de7cf8e0cd.png)

When i check the difference between the 2 exports, i have 2 files with different hash

![image](https://user-images.githubusercontent.com/19438099/178105252-19266d64-884a-4f78-9b6c-b4c0635e55cc.png)

Why gw is not able to convert correctly this floppy ? I made a mistake ?

Thanks for your help.

**Comment by keirf** [comment]
Can you zip the raw dump and upload it somewhere for me to download and look at? There's a few possibilities what it could be.

**Comment by Telev78** [comment]
Here : [my dump](https://mega.nz/file/eGxgVQLS#e_TlSOPyvvhSC8825EcYoDTAtCfFNu6J1hYw1JicAjE)

**Comment by keirf** [comment]
Thank you. Agreed it decodes okay in HxC tools, and also in my separate disk-utilities project. I will investigate further why greaseweazle's decoder is having problems here.

**Comment by Telev78** [comment]
ok thanks for your help
