### ISSUE TITLE
Implement Double Step

### ISSUE THREAD

**Issue by nretro** [keirf/Greaseweazle#21]
When reading a DD disk in an HD drive, every other track is garbage. Only reading every other track with gw.py saves half the time while reading and importing into HxC also is more than twice as fast, since analyzing broken tracks takes quite some time. 
I have attached a simple 4-line patch to read.py, which adds "--dstep" as an option.

[patch.zip](https://github.com/keirf/Greaseweazle/files/4308121/patch.zip)

**Comment by keirf** [comment]
I think we should speak in terms of cylinders of the disk, rather than cylinders of the drive.
