### ISSUE TITLE
macOS - Could not find SPS/CAPS IPF decode library

### ISSUE THREAD

**Issue by nicktones** [keirf/greaseweazle#218]
After installing GW on latest macOS and following the instructions to install the CAPSImage library, I get the error below when trying to write an IPF image. Can confirm that the library is installed in /Library/Frameworks.

** FATAL ERROR:
Could not find SPS/CAPS IPF decode library
For installation instructions please read the wiki:
<https://github.com/keirf/greaseweazle/wiki/IPF-Images>

**Comment by keirf** [comment]
Can you tell me what the library is called under /Library/Frameworks? Is there a CAPSImage.framework/CAPSImage? Or possibly in more recent releases one or other name component is CAPSImg instead of CAPSImage. If so, it will need a fix to Greaseweazle.

**Comment by nicktones** [comment]
The path is /Library/Frameworks/CAPSImage.framework/CAPSImage this is an alias to /Library/Frameworks/CAPSImage.framework/Versions/A/CAPSImage

**Comment by keirf** [comment]
And what sort of a Mac is it you are running on?

**Comment by nicktones** [comment]
M2 MacBook Air. Is CAPSImage Intel only?

**Comment by keirf** [comment]
Fortunately not, as source code was released and FS-UAE releases binaries for macOS ARM64. You can find the download link here: https://fs-uae.net/download#macosx

I think you need to download an unzip it. And relocate the `CAPSImg.framework` subfolder to `/Library/Frameworks/CAPSImg.framework`.

You also need Greaseweazle to search for the new library name. I have put a fix on branch `macos-caps`. You can install this branch into your Python environment as follows:
```
python3 -m pip install git+https://github.com/keirf/greaseweazle@macos-caps
```

**Comment by nicktones** [comment]
Perfect. I can confirm those steps work.

Thanks!!!

**Comment by nicktones** [comment]
Is the latest version of the tools searching for the framework? I've updated and am getting the not found error again.
