### ISSUE TITLE
version.py is missing

### ISSUE THREAD

**Issue by MarcoVogt** [keirf/Greaseweazle#22]
Hi,

the file `/scripts/greaseweazle/version.py` seems to be missing in the repository. It is only available in the snapshot .zip archives.
If you just clone the repo, it won't work unless you manually copy the `version.py` from the .zip.

Did I miss something, or is it a bug?

Cheers

P.S.: Awesome work. Really impressive! :+1:

**Comment by keirf** [comment]
It is auto-generated by the build script. You can **just** build version.py as follows:
```
# make -f Rules.mk scripts/greaseweazle/version.py
```
