### ISSUE TITLE
Just a suggestion for support of a slg46826

### ISSUE THREAD

**Issue by WarlockD** [keirf/greaseweazle#224]
I saw the other day on ebay a new SCSI emulator that uses this chip as a simple way to toggle the REQ line for sending/receiving data.  As I looked at the spec sheet I was kind of impressed.  It is duel rail so it easy supports 3.3 to 5v conversion, it has enough logic to decode most serial signals and can be reprogramed quickly with the i2c connection.  Best part is how detailed the data sheet is.  I have part of a LocalTalk to serial converter that works well so far and is handling a 4mb's connection.  Might be powerful enough to handle a MFM stream from a hard drive.

**Comment by keirf** [comment]
Interesting, but no plans to extend support to new hardware at this time. Thanks for the heads up however!
