### ISSUE TITLE
Same disk + different drives = different images

### ISSUE THREAD

**Issue by TzOk83** [keirf/Greaseweazle#24]
I have tried to image same Atari ST disk with 7 different drives:
SONY MFP-F11W-5DU (SONY8903)
SONY MFP-F11W-U0 (SONY9002)
TEAC FD-235HF A110-U5 (TEAC0302)
ALPS DF354H090F (ALPS0324)
NEC FD1231H (NEC9911)
MITSUMI D359T3 (MTS)
SAMSUNG SFD-321B (SAM0210)

Two first drives are original DD drives from Atari ST computers, latter ones are generic PC HD drives.
http://tzok.eu/ftp/mydisk.rar

Best non-Atari drive seem to be Samsung. The Alps drive was a factory new unit. Image made with Teac unit seems to be damaged.

**Comment by bradwh** [comment]
And the question is?

**Comment by keirf** [comment]
You won't ever get identical SCP dumps for successive dumps even using the *same* drive. Was that the question?

**Comment by TzOk83** [comment]
Yes - tat was the question - is this expected/normal? How to assess image quality? Program itself didn't return any errors in any of these images, but one of them seems to be bad.

**Comment by keirf** [comment]
You need to use analysis software to test/convert the SCP image. The SCP image dump just contains raw unchecked flux timings. So use HxC software (https://hxc2001.com/download/floppy_drive_emulator/HxCFloppyEmulator_soft_beta.zip) to visualise and convert.

Or on Linux use my Disk-Utilities project to convert (--format=ibm_mfm_dd): https://github.com/keirf/Disk-Utilities

Proper analysis in Greaseweazle itself is in development.
