### ISSUE TITLE
Cannot set track step for D88 reader

### ISSUE THREAD

**Issue by tdaede** [keirf/greaseweazle#255]
Because the D88 reader creates its own tracks, it does not respect the steps parameter for the format. This means that it assumes an 80 track drive and cannot use a 40 track drive to write 40 track images.

**Comment by keirf** [comment]
Is this really true? `step` should be respected by read/write/convert commands.

**Comment by tdaede** [comment]
I don't actually have a 40 track drive to test on right now, so I'll close this and reopen if I get one working.
