### ISSUE TITLE
macOS install fails

### ISSUE THREAD

**Issue by jluke1** [keirf/greaseweazle#260]
macOS install fails with error
"       File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'setuptools_scm'"

macOS 10.15.7
Python 3.10.8
pip 22.3.1 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
brew update ; brew upgrade has been run.

**Comment by keirf** [comment]
I've heard of occasional problems on Mac before, in just this way. I would expect the setuptools_scm dependency to be dealt with automatically but it seems not always to be. Try
`python -m pip install setuptools_scm`

**Comment by jluke1** [comment]
Thanks that fixed it. Fast response.

Thanks for all the excellent work.

Regards
John Luke

**Comment by keirf** [comment]
Thanks. I have updated the wiki to include this additional step. It should be harmless where it's not needed (already installed).
