### ISSUE TITLE
Blue Pill Direct - Not write

### ISSUE THREAD

**Issue by AidenShaw2020** [keirf/greaseweazle#268]
Hi all, i have issue with Blue Pill "Direct", when i try to write img to physical media:
![obrazek](https://user-images.githubusercontent.com/62829872/211843511-1f9d552d-f853-4cc9-bb15-5c99d2c78e5b.png)

Reading working OK:
![obrazek](https://user-images.githubusercontent.com/62829872/211843770-63664dd2-c388-4c7c-8b9e-4456eddaf487.png)
![obrazek](https://user-images.githubusercontent.com/62829872/211843894-d90bf94a-3d3a-4637-a54e-1673ccb3dac1.png)

Wirings is ok (without shortages), and i also tryied with dupont cables, and six other FDD's, but i have same experience.
![obrazek](https://user-images.githubusercontent.com/62829872/211845697-3c591cde-691e-4428-844c-96f6e75e1fe8.png)
![image0](https://user-images.githubusercontent.com/62829872/211844966-0dca776a-7cc3-4538-9093-262c9e02d27c.jpeg)
![image1](https://user-images.githubusercontent.com/62829872/211844969-c10a1516-1b96-4cf8-b193-3551d17f770d.jpeg)
![image2](https://user-images.githubusercontent.com/62829872/211844973-56a958f5-132f-4f8d-8149-c610e52d5c14.jpeg)

I use FW 1.2 and GW 1.4 (1.5 and Flux Engine have same issues).
Can you help me? Thanks.

**Comment by keirf** [comment]
The only extra lines that really matter for writing are WGATE (floppy pin 24, mcu pin B14) and WDATA (floppy pin 22, mcu pin B4). So make extra sure those are okay. Even better if you can put a scope or logic analyser on them. Also are you sure the disk you are testing is good and is high density?

**Comment by AidenShaw2020** [comment]
Hi @keirf, wirings for both pins Is OK, but thank you, for tapping me with logic analyser.
When I check both pins at same time, I have TTL only for B14, not B4:
<img width="1494" alt="pulse" src="https://user-images.githubusercontent.com/62829872/211914995-a4d864e9-7e72-47ed-9460-46a38ec33971.png">

For sure, I tried STM32 in Arduino IDE, and really, pin PB4 is not working.
I changed pin B4 to pin B5 in src/mcu/stm32f1/floppy.c:

`
/* WDATA: Pin B5, Timer 3 Channel 1, DMA1 Channel 3. */
#define gpio_wdata  gpiob
#define pin_wdata   5
#define tim_wdata   (tim3)
#define dma_wdata   (dma1->ch3)
`
, and now I have TTL on both pins, but writing still not working.
<img width="985" alt="pulse2" src="https://user-images.githubusercontent.com/62829872/211916151-3329101d-a03d-4cac-bcd3-570815f947f0.png">

Do I need edit pin somewhere else?

Thanks.

**Comment by keirf** [comment]
You can't just change pin. The chosen timer peripheral is only on the original pin.

First port of call would be the blinky test firmware to confirm that your blue pill is not a bad clone.

**Comment by keirf** [comment]
https://github.com/keirf/Greaseweazle/wiki/STM32-Fakes

And if you take the blinky firmware from an old Greaseweazle release that's better as the serial baud rate is incorrect in the version in most recent Greaseweazle releases. This version would do: https://github.com/keirf/greaseweazle/releases/download/v0.20/Greaseweazle-v0.20.zip

**Comment by AidenShaw2020** [comment]
I test blinky as first, and passed it. This version (0.20), works too.
https://user-images.githubusercontent.com/62829872/211920431-ee0a5c4b-0449-4d35-9152-6af17e096083.MOV

I also tried Bluepill Diagnostics, with pass:
![Bez názvu](https://user-images.githubusercontent.com/62829872/211920739-a85df446-bd02-431c-b7dc-57f501c85044.jpg)

**Comment by keirf** [comment]
Guess you need a new mcu or blue pill all the same

**Comment by AidenShaw2020** [comment]
I was afraid of that. I was glad to get a "working" one :(
Thanks for your support.

**Comment by AidenShaw2020** [comment]
Hi @keirf, after chip replacement, all is ok :)
For all thats have same problem as i, this is seller, where i bought replacements chips: https://a.aliexpress.com/_msFQ1sa

![5C2E08A4-C57D-4672-8C92-EEDB3702B036](https://user-images.githubusercontent.com/62829872/219408465-1e6a7bad-6e92-4e93-a99f-95fa162b7f31.jpeg)
![084561AA-3AED-427C-BE35-7E95C2701E8D](https://user-images.githubusercontent.com/62829872/219408508-21d19335-5fd8-4a29-b3b0-990bf50c484d.jpeg)
