### ISSUE TITLE
Feature Request: Support DENSEL to switch high density mode on F1

### ISSUE THREAD

**Issue by aliexpress987** [keirf/greaseweazle#287]
For the F1 version, I want to be able to support high density drives such that I am able to arbitrarily switch the density mode using DENSEL (PB9 on F1, Pin 2 on the drive connector).
Looking at the firmware code, PB9 is not addressed at all. So I was wondering what the default state of that Pin is.

Reasoning: My only remaining DD floppy drive broke, so I have to go on using HD drives reading DD disks now. So far I was unable to read any data from them, so I was wondering if the DENSEL output is by default setting (PB9 state) at HD mode instead of DD.

Could this please be implemented and a switch in the hosttools be provided?

Thanks,
Clark

**Comment by keirf** [comment]
Plenty of drives don't accept density select on pin 2. Leaving it to be explicitly set, as currently, is fine.
