### ISSUE TITLE
macOS - Could not find SPS/CAPS IPF decode library

### ISSUE THREAD

**Issue by nicktones** [keirf/greaseweazle#294]
I'm getting the could not find SPS/CAPS error after updating to 1.9 main branch. Had previously worked with the macos-caps branch.

Maybe 1.9 isn't searching for the framework in the right place?

**Comment by keirf** [comment]
It hasn't changed since the original fix.

**Comment by nicktones** [comment]
Strange. Nothing has changed on my end other than updating the tools.

**Comment by keirf** [comment]
What do you have under /Library/Frameworks

**Comment by nicktones** [comment]
<img width="1032" alt="Screenshot 2023-04-07 at 08 13 17" src="https://user-images.githubusercontent.com/2812641/230560863-ac9dc931-c5cc-4b99-b2bb-4b57b7959f14.png">

CAPSImg.framework is from link in wiki.

**Comment by keirf** [comment]
What is the Mac model and CPU? Can you show contents of CAPSImg.framework folder?

**Comment by nicktones** [comment]
<img width="1032" alt="Screenshot 2023-04-07 at 12 36 12" src="https://user-images.githubusercontent.com/2812641/230602440-418a5772-9d34-4d30-b1ba-db8f63efdb7f.png">

M2 MacBook Air 2022

**Comment by keirf** [comment]
I added a bit fo debug logging to a `macos` branch. You can install in your Python environment as follows
```
python3 -m pip install git+https://github.com/keirf/greaseweazle@macos
```

When you try to read an IPF it will print lines `Trying ...` and list the library paths being attempted. `/Library/Frameworks` is expected to be implicitly tried when the name `CAPSImg.framework/CAPSImg` is passed. Perhaps it isn't tried now for some reason? There certainly isn't much in that folder on your system. Perhaps `/System/Library/Frameworks` is more popular? You could also try in your home folder: `~/Library/Frameworks`

**Comment by nicktones** [comment]
Thanks for this. Output from debug build attached - doesn't seem like it's looking in the right place. Under macOS Ventura /System/Library/Frameworks isn't writable and there isn't a frameworks folder in the home library.
<img width="1089" alt="Screenshot 2023-04-07 at 13 26 18" src="https://user-images.githubusercontent.com/2812641/230608596-97959f31-b4b6-46f4-adb6-aee479136fdc.png">

Looks like it's looking in the app folder maybe?

**Comment by keirf** [comment]
Yes it's looking explicitly in the app folder. You could put it exactly there at least to see whether that works.

Alternatively try the other things that ought to be on the search path by default:
- `/System/Library/Frameworks`
- `~/Library/Frameworks`

**Comment by keirf** [comment]
Oh I see `/System/Library/Frameworks` doesn't exist... You could try creating the one in your home folder. `mkdir -p ~/Library/Frameworks`

You can delete it if it doesn't work.

**Comment by keirf** [comment]
You can also now reinstall the tools same as before:
```
python3 -m pip install git+https://github.com/keirf/greaseweazle@macos
```

I have *explicitly* added the `/Library/Frameworks` path.

**Comment by nicktones** [comment]
Amazing - explicitly adding the folder worked with the new build. Thanks!

FYI - creating the Frameworks folder in the home folder and adding there didn't work.

All sorted with the latest debug build. Thanks again

**Comment by keirf** [comment]
How weird. I'll add that for the next release. Does no harm.

**Comment by nicktones** [comment]
Indeed. Could be a change in latest Ventura update I guess.

Thanks again.

**Comment by keirf** [comment]
This is now in master branch:
```
python3 -m pip install git+https://github.com/keirf/greaseweazle
```
