### ISSUE TITLE
support to amiberry inside raspberry pi amibian like a real floppy

### ISSUE THREAD

**Issue by Toolkitman** [keirf/greaseweazle#304]
Dear developers,
I'm an owner of greaseweazle v4 and i have built over it an AMIGA 1200 raspberry pi 4B prototype. Everything works also build floppy images from real floppy inside linux amibian, but what i would like to have better is pure hardware support for floppy inside amiberry and workbench os,  a friend say to check if there’s a way to do raw sector access to do this stuff.

Thank you for reading

**Comment by keirf** [comment]
Amiberry supports the drawbridge floppy acces feature by Rob Smith. Allows direct access to floppy from the emulator via Greaseweazle. That should do the trick?

**Comment by Toolkitman** [comment]
Yes thank you!

Inviato da iPhone

**Comment by Toolkitman** [comment]
I have give a look to it it seems drivers are only available for windows os. In this case we need amibian linux drivers.

Inviato da iPhone

**Comment by keirf** [comment]
The support is built in to recent Amiberry releases. You don't need to download drivers.

**Comment by Toolkitman** [comment]
Cool thank you! Is needs soldering and a particular floppy? I have for example a modded pc floppy to amiga.

Inviato da iPhone

**Comment by keirf** [comment]
No. PC drive connects to Greaseweazle (floppy ribbons and power). Greaseweazle connects to Pi (USB).

**Comment by Yserra** [comment]
I confirm it works. 
I installed a Raspberry Pi 4B + Greaseweazle V4 into an Amiga 1000 case. The floppy drive is connected to the Greaseweazle, the Greasezweazle is connected to the Raspberry Pi, Amiberry runs on the Raspberry Pi, Amiberry reads (an boots from) real Amiga floppy disks inserted into the floppy drive. 
There is no driver to install. It just works. 
By the way, it's not perfect. Several "trackdisk" games hang. But simple AmigaDos disks are working.

**Comment by Toolkitman** [comment]
Awsome, i have the same system in an amiga 1200 case and keyboard but with
AMIBIAN OS and this feature dont work.
Can you tell me where to download amiberry os that you use? and if there is
a guide to install it if there are some linux commands to add
Thank you again you are the best!

Il giorno sab 29 apr 2023 alle ore 01:32 Yserra ***@***.***>
ha scritto:

**Comment by Yserra** [comment]
I think Amibian is quite obsolete now (I would even say "abandoned since some years") ; the Linux it is based on is too old for the latest versions of Amiberry. the latest Amiberry versions (go to https://github.com/BlitterStudio/amiberry/releases/tag/v5.6.0) require Debian/RPI-OS Buster (32-bit) or Bullseye (64-bit). I'm sure you will find lot of tutorials elsewhere on the web to install all the required software (Linux + Amiberry) onto your Raspberry Pi. I personally use Retropie, a "plug'n'play" distribution.

**Comment by Toolkitman** [comment]
Ok i will check.

Inviato da iPhone

**Comment by Toolkitman** [comment]
I have installed amiberry on the new raspbian distro and i get an error disk bridge track 0 not found can you help? Greaseweazle is working under linux gw command.

Inviato da iPhone

**Comment by keirf** [comment]
Maybe drive select is set wrong (eg A vs B)

**Comment by Toolkitman** [comment]
In amiberry or in gw? I tryed in amiberry with b in gw info i think it is drive 0

Inviato da iPhone

**Comment by keirf** [comment]
Well, I've never used Amiberry so to be honest I don't know. There should be a drive select option if it's anything like UAE floppybridge. But the place to ask for support is Amiberry.

**Comment by Toolkitman** [comment]
Ok thank you

Inviato da iPhone
