### ISSUE TITLE
Epson SD-600 problem with STM32F103C8T6 Direct Connection

### ISSUE THREAD

**Issue by ILAHWWINC** [keirf/Greaseweazle#31]
I want to use a "Blue Pill" with Dupont direct wiring on a Epson SD-600 5.25 Floppy drive.
I can read disks, but the disk analyze shows multiple errors (see dump).

When i connect the same Epson drive with a STM32 "Blue Pill" adapter board and a floppy flat cable the result is fine (see dump).

I can not find out what makes the difference.
![gw-dump2](https://user-images.githubusercontent.com/29736419/81496798-933c5b00-92ba-11ea-993f-c07b2de21b98.jpg)

![gw-dump1](https://user-images.githubusercontent.com/29736419/81496796-8f103d80-92ba-11ea-9811-958f1b65aa38.jpg)

**Comment by keirf** [comment]
Does the adapter board have the 4x1k resistors attached?

**Comment by ILAHWWINC** [comment]
Yes. It is one out of your production.

**Comment by keirf** [comment]
Then either the dupont wires are not making good connection or, more likely, you need 1k pullups on inputs from the drive.

**Comment by ILAHWWINC** [comment]
I tried with a 3.5 Floppy, Epson MPF-920-E. 

There is no problem. It seems to be a problem with the specific combination floppy-blue pill/dupont.

**Comment by keirf** [comment]
Lack of 4x 1k pull ups on the inputs. Add them and it will work fine.

**Comment by ILAHWWINC** [comment]
To be sure:
At „Blue Pill“ connect B6/INDEX, B7/TRK0, B8/WRPROT, B2/DKRD over resistor 1K to 5V. Right?

**Comment by keirf** [comment]
Yes. Each gets a 1k resistor as you say. Four resistors total.

**Comment by ILAHWWINC** [comment]
I can confirm that the problem is solved with the pull up resistors.
Maybe a note telling about the pull ups in the Hardware Assembly section would be helpful.

**Comment by PicoElements** [comment]
In this special case with the SD600 , did you realized hot to slow down to 300 rpm ? Or you used  pin 2 L with success?
