### ISSUE TITLE
Add option to erase before write

### ISSUE THREAD

**Issue by sdsnatcher73** [keirf/greaseweazle#313]
I've noticed that writing can fail if existing flux is not erased before the write. so for now I perform a gw erase before a gw write action. It would be nice if the write action had an option to erase the track prior to writing.

**Comment by keirf** [comment]
New option `--pre-erase` is added on branch `issue-313`, pending testing.

**Comment by sdsnatcher73** [comment]
I tried this one and it seems to do the job (although it's hard to predict when writing fails without the erase).
