### ISSUE TITLE
Ggreaseweazle v4 and chinon fb-354

### ISSUE THREAD

**Issue by premiero** [keirf/greaseweazle#329]
Hi there.  I just tried to use my fully working Chinon FB-354 drive from real Amiga 500 and i've got stuck.
I am using original straight cable from Amiga as well as originall power cable from Amiga. 

gw info gives me:

Host Tools: 1.13
Device:
  Port:     COM3
  Model:    Greaseweazle V4
  MCU:      AT32F403A, 216MHz, 96kB SRAM
  Firmware: 1.3
  Serial:   GW0045C5927048000007A5070F
  USB Rate: Full Speed (12 Mbit/s)

so gw device is recognized. But every time i try to read anything from floppy a green diode lights up and then an error:

Reading c=0-79:h=0-1 revs=1.1
Format amiga.amigados
Command Failed: GetFluxStatus: No Index

What am I doing wrong? Is this some power related issue?

**Comment by premiero** [comment]
Well i tried all --drive A/B/0/1/2 and nothing works. I am not sure how this fdd is powered, but measuring output with my multimeter on Amiga motherboard gives me +5V/GND/GND/+12V. So maybe it's really missing +12V. Thanks @keirf

**Comment by keirf** [comment]
If it's an old full height Chinon drive then it does require 12v

**Comment by premiero** [comment]
![obraz](https://github.com/keirf/greaseweazle/assets/27424909/c3a16d4a-1ae5-4958-b0c1-7b8d6f70629f)

**Comment by keirf** [comment]
I'm almost certain that drive needs 12v. Plausible methods for powering include a Molex PSU plus Molex to floppy adapter. Or use an ATX psu. Advantage is low watt ATX PSUs are dirt cheap and good quality (eg Delta PSUs on eBay) and you just need to bridge the green wire to ground to turn them on

**Comment by keirf** [comment]
Or get yourself a PC 3.5 drive. They are basically always needing only 5v.

**Comment by premiero** [comment]
> Or get yourself a PC 3.5 drive

That is the primary goal + printing the case, but atm i just wanted to test the device. :)
