### ISSUE TITLE
possible regression gw 1.15

### ISSUE THREAD

**Issue by Telev78** [keirf/greaseweazle#342]
Hello,

I updated my version of GW from 1.12 to 1.15, and now i have an error message when i use this command line :
`gw convert --format ibm.1440 test\track00.0.raw test.ima`

> gw convert --format ibm.1440 test\track00.0.raw test5.ima
> Converting c=0-79:h=0-1 -> c=0-79:h=0-1
> Format ibm.1440
> Traceback (most recent call last):
>   File "C:\Users\runneradmin\AppData\Roaming\Python\Python311\site-packages\cx_Freeze\initscripts\__startup__.py", line 130, in run
>   File "C:\Users\runneradmin\AppData\Roaming\Python\Python311\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
>   File "gw.py", line 3, in <module>
>   File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\site-packages\greaseweazle\cli.py", line 69, in main
>   File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\site-packages\greaseweazle\tools\convert.py", line 177, in main
>   File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\site-packages\greaseweazle\tools\convert.py", line 26, in open_input_image
> TypeError: KryoFlux.from_file() takes 2 positional arguments but 3 were given

The same command line work with the 1.12 version

**Comment by keirf** [comment]
Good catch. I've re-rolled v1.15 to include this fix, so just download the v1.15 version again.
