### ISSUE TITLE
Release 1.15 changed checksums for downloads?

### ISSUE THREAD

**Issue by VorpalBlade** [keirf/greaseweazle#343]
I package greaseweazle for Arch Linux AUR. Apparently today greaseweazle changed the checksums for the 1.15 .zip download (or perhaps re-released it). This creates havoc for downstream packagers. It is much better to issue a different release (e.g. 1.15.1 or 1.16).

**Comment by keirf** [comment]
Sorry about that. 1.15 is now burned since I cannot rewind the history and produce an identical zip file. So I have deleted it entirely, and uploaded 1.15.1 in its place.
