### ISSUE TITLE
0.17 update --bootloader doesn't seem to be working in the windows .exe

### ISSUE THREAD

**Issue by M1kerochip** [keirf/Greaseweazle#35]
running
gw update --bootloader
gives the following:
** Bootloader v0.16 [F1], Host Tools v0.17
Greaseweazle is in Firmware Update Mode:
 The only available action is "update" of main firmware
 Remove the Update Jumper for normal operation

**Comment by keirf** [comment]
I need to mention this in the wiki: You update the bootloader in normal mode.

**Comment by keirf** [comment]
Please confirm that works for you, and I will do so.

**Comment by keirf** [comment]
Apart from that, you don't need to update the bootloader as a matter of routine. There's been no bug fixes to the F1 bootloader at all.

**Comment by M1kerochip** [comment]
Yup, works fine!
(I was just testing, is all. Thanks!)

**Comment by keirf** [comment]
Great. I have updated the wiki.
