### ISSUE TITLE
Add Greaseweazle write enable jumper setting to `gw info`

### ISSUE THREAD

**Issue by cefiar** [keirf/greaseweazle#370]
Any chance that we can add the status the write enable jumper setting to `gw info`? 

Spent way too long trying to figure out why writing wasn't working before I realised that I changed the jumper a while ago to avoid accidentally writing to disks.

**Comment by keirf** [comment]
Unfortunately the jumper is completely invisible to firmware and software. It's a simple break in the write-gate signal line to the floppy drive.
