### ISSUE TITLE
Greaseweazle gives Command Failed: Motor: Invalid unit number

### ISSUE THREAD

**Issue by jamesy0ung** [keirf/greaseweazle#378]
Hi, my greaseweazle F1 is giving the following error when used with an Amiga drive and specifying drive 0

PS C:\Users\James\Downloads\greaseweazle-1.16.2-win64\greaseweazle-1.16.2> .\gw.exe clean --drive 0
Command Failed: Motor: Invalid unit number

Using all latest software, it works with a pc drive but not the amiga drive

**Comment by keirf** [comment]
F1 doesn't have flexible drive assignment. It's pretty much statically wired to address PC drives, A or B, without need of --drive parameter.

Amiga drive may also fortuitously work even though drive select will be driven by Greaseweazle's motor signal. Usually motor and select are driven together so could just work. In short just drop the --drive=0 and see what happens.
