### ISSUE TITLE
Proposal for slightly more elaborate documentation

### ISSUE THREAD

**Issue by Yserra** [keirf/greaseweazle#395]
Hi Keir, 
I wish you an happy new year. 

Since I find this page https://github.com/keirf/greaseweazle/wiki/Getting-Started a bit frustrating, I've tried to write a little more comprehensive documentation. See the attachment. 

Feel free to take from it as much as you like. 

Please note: English is not my mother tongue (I'm French) and this text may contain language errors.

Hope it could be useful.

Best.
[GreaseweazleDoc.zip](https://github.com/keirf/greaseweazle/files/13854625/GreaseweazleDoc.zip)

**Comment by keirf** [comment]
Wow, that's a lot better!

**Comment by Yserra** [comment]
I have no idea. Actually, I wrote this with Microsoft Word and saved it as .html. I tried to convert the .docx to .md with Pandoc, but it was a bit of a mess (the tables, the images went away, the font was non-sense). Would you have any recommandation to share that would help me produce the format you are expecting?

**Comment by keirf** [comment]
Thanks. I can do a lot more with the docx original file. For example pandoc produces halfway sensible Markdown which I can tweak.

**Comment by keirf** [comment]
See what you think of the new Getting Started wiki page!
https://github.com/keirf/greaseweazle/wiki/Getting-Started

**Comment by keirf** [comment]
Images currently missing. To be added :)

**Comment by Yserra** [comment]
Thank you Keir, It's fantastic! I'm honored to be part of this great adventure :)
