### ISSUE TITLE
Easy way to test floppies

### ISSUE THREAD

**Issue by kepak1** [keirf/greaseweazle#411]
I got bunch of 3.5 inch floppies, and i wold test it to use in different systems ( amiga, atari ST, PC). Can i use Greaseweazle to test it for bad sectors?
Some of them I think would work better on 720k than 1.44

**Comment by keirf** [comment]
Yes if they are regular system disks, then you can do format analysis as you read the disks. For example:
```
gw read --format=ibm.720 name.img
```
Will expect 720k PC format and give you a summary of bad sectors at the end of the dump. This of course presupposes that you know the expected format of each disk! It's a bit more work if you're uncertain.
