### ISSUE TITLE
Format td0 : not able to create a disk 

### ISSUE THREAD

**Issue by sappas2** [keirf/greaseweazle#413]
Hello, i'm trying to make a boot c/pm disk for my epson qx-10,
a teledisk format exist in greaseweazle : td0, but i'm not ablle to create it until i'm using hcx floppy emulator software to export .scp file.
By the way, why to create .scp, it doesn't work in my QX-10, it's not work, maybe an another problem from the QX-10.  

http://www.vintagecomputer.net/fjkraan/comp/qx10/disklibrary.html
And particulary this file http://www.vintagecomputer.net/fjkraan/comp/qx10/diskimages/QX10CPM_MF.zip

I'have created 2 adf disk with success for a Amiga 1000...
I've version 4.1 upgrade to firmware 1.5

**Comment by keirf** [comment]
What happens when you try to write the td0 file (I assume CPM22M1.TD0) directly using gw tools? The file appears to be imported okay, as a 16 sectors-per-track 40-track 2-sided image.

There should be no need to do prior conversion to scp.

My guess, verification fails when you try to write the td0. When you convert to scp, the write is not verified (gw cannot do a verified write of scp). Hence the write appears to work, but doesn't really.

**Comment by sappas2** [comment]
You're right it's verify failure, i've changed 3 times from floppy drive et 2 times the cable, maybe the card and a cold junction ? 
Powersupply for floppy are external, an atx one

**Comment by keirf** [comment]
What sort of drive and what sort of disk? The image is double density and so will need a double density disk.

**Comment by sappas2** [comment]
Chinon FZ502 cleaned head and rail reoil and JU-455  5(*2) Mitsubishi DS DD soft sectored, 40 tracks, never used.
Can i abort verification as --retry=0 i cannot retrieve if  i've seen it 
In GW 1.16.3 after reading TD0, why "Writing c=0-81:h=0-1" for 40 cylinders ?

**Comment by keirf** [comment]
Okay, so both drives are double-density and 40-track as required. Are the drives known to work? Can you read an existing known good disk, if you have one?

You can specify `--no-verify` to disable verification.

The `Writing c=0-81:h=0-1` is misleading actually. This is the default range of tracks considered, however nothing will be written for tracks not defined in the TD0 file, so in fact only c=0-39 will be written and your drive won't get its heads stepped out of range.

**Comment by sappas2** [comment]
I can't read an existing disk, i close this issue, many thanks
