### ISSUE TITLE
8" Floppy: extra empty tracks in the image

### ISSUE THREAD

**Issue by gotcha-z80** [keirf/greaseweazle#415]
Hello,

When I dump a 8" floppy that has 77 tracks as a SCP image, I get extra empty tracks. It's not always the same number. Usually, I get between 126 and 130 tracks in total instead of the expected 77 tracks.
Any idea what is going on ?

The command I use for a single sided floppy is the following:
```
gw read --drive=1 --revs=3 --tracks=c=0-76:h=0 test.scp
```

I attach an example displayed with HxCFloppyEmulator

![dump8pouces](https://github.com/keirf/greaseweazle/assets/114250129/8513fffb-8b47-4021-b3d0-9c417752594d)

**Comment by keirf** [comment]
There is confusion around how to represent a single-sided SCP image. You could try latest beta/snapshot of HxC software, or you can produce a "legacy" single-sided SCP image: `gw convert test.scp test_legacy.scp::legacy_ss`

**Comment by keirf** [comment]
Yes, I believe we came to agreement some time ago. I'm not sure how often the non-beta download gets updated -- the beta is often the best one to go for.
