### ISSUE TITLE
PC disk types

### ISSUE THREAD

**Issue by AngelDevIndie** [keirf/greaseweazle#416]
Hello Keirf,
Thank you for your work. I'm dumping all the PC games I have. 

I think I have seen an error in the parameter that is passed to the program. It's not important, but I think there was a confusion with the numbers.

In _SCP.py_ the _DiskType_ values for PC are:
![imagen](https://github.com/keirf/greaseweazle/assets/63190654/a5e708b4-ee15-4013-bbfc-458a51e2d96d)

In the specifications for **SCP** files on the cbmstuff.com website:
![imagen](https://github.com/keirf/greaseweazle/assets/63190654/f8342f9c-c922-4b80-9e47-9a9905025bd8)

So the correct parameter should be:
**ibmpc-360k**

I don't know if this is the case, but maybe you got confused.

Thanks again, and I hope I helped you.

Best regards.

**Comment by keirf** [comment]
Yes, that's a typo, thanks for the report!

**Comment by FrankieTheFluff** [comment]
Hi, could you please also check the added atarist-dshd and atarist-sshd?
https://www.cbmstuff.com/downloads/scp/scp_image_specs.txt

Greetings Frank
