### ISSUE TITLE
NoIndex

### ISSUE THREAD

**Issue by Macgician** [keirf/greaseweazle#424]
I bought three Greaseweazle. One is running, two are not. Im using the same drives, same cables, same disks, same commands. And still two Greasewazle are not working whilst one is doing perfectly fine. Any suggestions?

**Comment by Macgician** [comment]
oh I also tried an extern PSU for the drives.  Im using an Alps DF354 and a Mitsumi. Both are running at my working Greaseweazle but not at the others...

**Comment by keirf** [comment]
What sort of commands are you trying? What sort of Greaseweazles? Where did you get them?

**Comment by Macgician** [comment]
For example gw update works with all three. 

Gw rpm (and all other that are trying to use the floppy) only works with one Greaseweazle (but with all floppies)

They are all Greaseweazle 4

And I bought them at eBay. One never worked the other one used to work and then suddenly stopped working (without changing anything)

I can use gw update on all of them. The two that doesn't work have 1.5 the working one has 1.3. I tried to downgrade one to 1.3 again. Whilst I can still flash a new fw it still won't work

**Comment by keirf** [comment]
Well, since you can literally do a side by side swap-out comparison, I'd say the non working ones have hardware faults. Unusual to find two not working though, they're quite reliable generally.

**Comment by keirf** [comment]
If you're in the UK you could send them to me to take a look at. Otherwise contact your seller if you didn't buy them so long ago

**Comment by keirf** [comment]
In fact you could send them to me regardless but I'm UK based

**Comment by Macgician** [comment]
"They are quite reliable" that's actually what I thought, too. Also because they can still be flashed as I assume if anything would take damage then the AT32s.

**Comment by keirf** [comment]
That's assuming they are originally from me which they probably are but link to your reseller so I can know for sure.

**Comment by Macgician** [comment]
> In fact you could send them to me regardless but I'm UK based

I'm from Germany. I bought them some time  ago and never complained as I thought I'm just using wrong commands. I missed the two week time to send it back and then bought another one which then worked and stopped working. This is a year ago now 🙈

**Comment by Macgician** [comment]
> regardless

I'm gonna check the shipment costs. I guess there will not be any customs duty?

**Comment by keirf** [comment]
Email keir.xen@gmail.com to arrange return. Customs should not be a problem EU to UK at least, vice versa is more pot luck. Please also let me know by email which eBay seller you purchased from.

**Comment by keirf** [comment]
Hi there, Any update? To be clear -- I will repair/replace the units you send me, and cover return shipping cost, if the units are purchased via one of my resellers.

**Comment by keirf** [comment]
Sorry I did not receive your email. Check spelling?

**Comment by Macgician** [comment]
Hm, I just tapped on your email address and wrote my mail. Have you checked SPAM?

**Comment by keirf** [comment]
Yeah I had a good look round my mailbox. Nothing. Weird huh. No typo my end either, this is copy-pasted from my mailbox: keir.xen@gmail.com

Maybe it will arrive later haha.

**Comment by Macgician** [comment]
Just resent it

**Comment by keirf** [comment]
I received the re-sent version. I will reply shortly, after work meetings :(
