### ISSUE TITLE
Trackloading or custom loading fails in WinUAE

### ISSUE THREAD

**Issue by pawpaw91** [keirf/greaseweazle#443]
While the ADF disk image is fully supported in WinUAE, it is not the case with a real floppy. Copying the image from the disk back to .adf makes it work again.
Tested with “Soccer Kid disk 1” (originally disk “0”), Greaseweazle v. 4.1 & latest WinUAE (x86, x64) with Floppybridge on two different machines, a PC running windows 10 and a laptop with windows 8.1.
Choosing the “Stalling” option in Floppybridge yields slightly better results, with Krisalis Software logo and a part of the intro being properly displayed. Then, the system is resetting.

**Comment by keirf** [comment]
You need to raise this issue on the Floppybridge tracker: https://github.com/RobSmithDev/FloppyDriveBridge
