### ISSUE TITLE
Driver for windows 7 needed

### ISSUE THREAD

**Issue by crestr1** [keirf/greaseweazle#467]
is this available anyplace. all the software and the GUI appears to work under w7

**Comment by keirf** [comment]
Use zadig to set up usbser driver for Greaseweazle device. And use the win32 build of the tools.

**Comment by crestr1** [comment]
Tks K, Any bad experiences of this cohabiting with the driver for kryoflux under w7 ?
Been having lots of unrelated issues with Kyroflux it seems to have internal clock speed preservation problems (pic attached). This is why I'm trying greaseweazle
![DSCN5098R](https://github.com/user-attachments/assets/cf68db45-b1d6-434b-8ff7-15d5049d818e)

**Comment by keirf** [comment]
Should be fine. Not sure what those KF errors mean, could be bad disk or drive?

**Comment by crestr1** [comment]
Both the disk and drive are good, this happens a lot when recovering from 8" drives
I put the missing data error streams in KF down to meta-stability someplace in its logic when a data edge corresponds with a clocking edge.
eg: https://nandland.com/lesson-13-metastability/
