### ISSUE TITLE
Suggestions for wiki doc improvement

### ISSUE THREAD

**Issue by fplanque** [keirf/greaseweazle#478]
I believe [this page](https://github.com/keirf/greaseweazle/wiki/Supported-Image-Types) should receive more details for each format or maybe have each format link to a subpage.

I don't know all the formats, but here is some info I would have liked to find on this page:

### IMG, IMA, DSK (Generic suffixes for IBM FM/MFM Raw Sector)

This format stores the payload data of all sectors concatenated, with no separators and no metadata.

The sectors appear in increasing logical order of Track #, Head #, Sector #.

For example on a double sided, 80 track, 9 sectors format, the order of sectors in the fille be:

- T0 H0 S1
- T0 H0 S2
- T0 H0 ...
- T0 H0 S9
- T0 H1 S1
- T0 H1 S2
- ...
- ...
- T79 H1 S9

### IMD (IBM Sectors)

I am making this up but I guess it's something like:

In addition to the payload data of each sector, some meta data is also included for each sector, namely:

- Track #
- Head #
- Sector #
- Data CRC
- ...

## Raw Image Types:

General note for raw formats: if you want to store the real raw flux data from disk, you must specify `--raw` in the command line, for example:

`gw read --drive 0 --raw --tracks c=0-39:h=0 destination_file.scp`

If you specify a `--format` instead of `--raw`, the file will store digitally regenerated "perfect" flux data (and bad sectors with be filled with `==[BAD SECTOR]==`. This is probably not what you want when saving raw flux data.

_One thing that is still unclear to me: do these raw formats include multiple reads of the same track? (I believe so but I'm not sure)_

### Kryoflux (Raw Flux)

Currently listed as `-Kryoflux (Raw Flux)` but there is no `.kryoflux` listed in `gw read --help` contrary to all other formats.  Does it use another extension?

### Best format for archival

If you have old disks containing errors that you wish to archive before they get even more errors, the most complete format to save them in (in order to try and fix them later) is: ????

Example command line:

! Make sure to include all tracks (there might be more than 80) and both sides of the disk if it's double sided.

## Bad sectors

- If you read a disk with `--raw`, the bad data is preserved in the output file
- If you read a disk with `--format`, bad sector (eg: wrong CRC) is replaced by a pattern of `==[BAD SECTOR]==`

**Comment by fplanque** [comment]
Also for the Troubleshooting FAQ page:  https://github.com/keirf/greaseweazle/wiki/Troubleshooting-FAQ

## Commands fail with 'Track 0 not found' or 'No Index'

- Another noob mistake is to connect the ribbon cable in reverse. Do NOT trust the notch on the connector and/or cable. Look for pin 1 on the Greaseweazle and for pin 1 on the drive.
- Note: connecting the cable in reverse typically doesn't damage the drive (no guarantees though) but it definitely will make you feel like nothing is working.
- When a drive doesn't spin and you're not sure whether the motor is broken vs your connection is wrong, you can also try to move the head with `gw seek 10` for example.

**Comment by keirf** [comment]
I will get these merged into the wiki. Thanks!

**Comment by fplanque** [comment]
## Command Failed: GetFluxStatus: No Index

- First things first: check that you have inserted a floppy into the drive ;)

**Comment by keirf** [comment]
I think I have got all these into the wiki now!

**Comment by fplanque** [comment]
> The sectors appear in increasing logical order of Track #, Head #, Sector #. 

I think I wrote this in the wrong order and it should be Track #, Sector #, Head #. (?)

---

> [Kryoflux](https://github.com/keirf/greaseweazle/issues/478#kryoflux) (Raw Flux, multiple revolutions per track)

For newbies who read the doc for the first time, this would be clearer as 

[RAW Kryoflux](https://github.com/keirf/greaseweazle/issues/478#kryoflux) (Raw Flux, multiple revolutions per track)

So that it is consistent will all other formats that match the filename extension.

---

Finally, it would be really useful to provide some hints about:

- What's the difference between RAW Kryoflux and SCP ?
- Is one more complete than the other? (especially in case you want to archive disks that already have errors and you want to archive them before they get more errors, all in the hope that there will be tools to try to correct the errors at some point in the future)
