### ISSUE TITLE
Detect no flux and complain about it

### ISSUE THREAD

**Issue by drdpj** [keirf/greaseweazle#48]
Sony F920, 3.5" HD drive (this does work fine with the F1 hardware), reads of high density and standard density disks are resulting in 8kb SCP files. See attached.
[test2.zip](https://github.com/keirf/Greaseweazle/files/4971149/test2.zip)

**Comment by keirf** [comment]
```
$ python3 ~/Greaseweazle/scripts/misc/scp_info.py test2.scp | grep flux= | grep -v flux=0 | wc -l
0
```

**Comment by keirf** [comment]
There are no flux values in the SCP file at all. Nothing was seen on RDATA.

This Greaseweazle hardware is working okay with other drive(s)?

**Comment by keirf** [comment]
For a PC drive with a straight cable I would expect `--drive b` rather than `--drive 0`. Unless the drive-select configuration has been messed with on the drive PCB.

**Comment by keirf** [comment]
Seems to me a few possibilities: Bad Greaseweazle, bad drive, bad cable, bad config.

How many can you discount?

**Comment by drdpj** [comment]
It's bad GW I think, buzzed out OK but just looking through offspring's microscope I wasn't convinced by the soldering on the QFP.  Sorry - I was a bit quick off the mark there!

**Comment by reinauer** [comment]
Is there a way to catch this in software? I ran into the same issue. If absolutely no data is coming, the error message should read "Go, resolder the STM32, you dummy" ;)

**Comment by keirf** [comment]
Software these days displays the amount of flux read from each track. So `0 flux in 0.00ms` is probably clue enough.
