### ISSUE TITLE
Issue with latest bitarray releases (>3.0.0)

### ISSUE THREAD

**Issue by sdsnatcher73** [keirf/greaseweazle#502]
On my MacBook with python 3.13 installed through brew I recently started running into issues when GreaseWeazle tries to read or verify written data:

Format pc98.2hd
Writing c=0-76:h=0-1
T0.0: Writing Track (Flux: 166.7ms period, 183.3 ms total, Terminate at index)
** FATAL ERROR:
**'bitarray.bitarray' object has no attribute 'itersearch'**

Going back to earlier GW releases did not fix it while those worked before.

Okay seems itersearch and iterdecode were removed in 3.0 of the bitarray, check the [changelog](https://github.com/ilanschnell/bitarray/blob/master/CHANGE_LOG). The search and decode functions now return an iterator. I guess GW could require version 2.9.3 of bitarray in some way and a future 1.21 could switch to 3.0?

**Comment by keirf** [comment]
Either I need to require >=3 and fix the code, or I need to require <3. I guess the latter is simpler for now. Let me see.

**Comment by keirf** [comment]
Should be fixed in release tags `v1.21` and `latest`.

**Comment by branchonequal** [comment]
I "fixed" it locally by replacing all occurrences of `itersearch()` with `search()` (according to the [bitarray version 3 transition document](https://github.com/ilanschnell/bitarray/blob/master/doc/bitarray3.rst)) which seems to work (I could at least write a disk without issues).

**Comment by keirf** [comment]
On v1.21 you should be able to uninstall the bitarray package and then greaseweazle installation should pull in the required earlier version.
