### ISSUE TITLE
Memotech diskdef ?!

### ISSUE THREAD

**Issue by gilmod714** [keirf/greaseweazle#506]
hello,

is there support in diskdefs for reading Memotech MTX512 floppy disks ?!

I have tried adding the geometry , but it didnt work ..
Thank you,
Gilmo

this is what I tried in diskdefs.cfg

disk Memotech-07
    cyls = 80
    heads = 2
	tracks *  ibm.mfm
	secs = 16
	bps = 256
	rate = 250
	rpm = 300
	id = 1
	interleave = 3
	end
end

**Comment by keirf** [comment]
How does it fail? Can you take a raw dump (gw read with no --format to a raw flux format such as scp).

**Comment by gilmod714** [comment]
ok , I will upload some screen shots now ..

**Comment by gilmod714** [comment]
Ok, Thanks Keirf

If I read SCP - unspecified format .. it read the image .. but the resulting image writing it back doesn't work on MTX512

If I do "Memotech type 7"  read , I get a bunch of errors .. (pic #3)

![IMG_20241110_235625 (Medium)](https://github.com/user-attachments/assets/db3177d1-de39-409e-b573-64e0d2109899)


![IMG_20241110_235631 (Medium)](https://github.com/user-attachments/assets/35e2efd1-45ef-4ec3-ab88-4e3a23d66883)


![IMG_20241111_000105 (Medium)](https://github.com/user-attachments/assets/7354e5a3-472e-4f1b-92f2-ec9148628f46)

**Comment by keirf** [comment]
Can you share the SCP image file? Then I can inspect it.

**Comment by gilmod714** [comment]
of course .. please see attached .. this is mostly a blank MTX512 disk with only one file on it called "sdxboot.bas"

the first 2 tracks are CPM system bytes ..

[mydisk.zip](https://github.com/user-attachments/files/17704440/mydisk.zip)

**Comment by keirf** [comment]
Load that SCP into HxC software and look at tracks in "stream view" and you will see the data is very noisy. Possibly your drive supports double- and high-density, selected by pin 2. So try adding `--dd L` to your `gw read` command line(s). I think your disk format specifier is probably correct.

**Comment by gilmod714** [comment]
Ok , yes I do believe that my drive supports both DD/HD , it's a 3.5" Sony MPF920

I will try what you have suggested,

Thank you Keir

**Comment by keirf** [comment]
Oh 3.5-inch drives usually auto-detect the density. They don't take a mode select on pin 2.

It is weird how your dump is worse on the outer (lower-numbered) tracks. So nonetheless it still feels like it could be density related. Suffice to say it is no wonder the software can't retrieve sectors reliably, anyway.

**Comment by gilmod714** [comment]
ok, so I changed the floppy to another unit I have "Panasonic JU-256A" .. and I am not getting any errors reading/writing anymore (so I guess Memotech type07 diskdef is correct ... I was able to write a ready-made .hfe image and it works on the MTX side ... however, reading the same disk back and comparing the 2 images in hex-editor , there are some differences in bytes ... 

I am using HD floppies by the way with hole covered , since I don't have any DD disks , if that's makes a difference..

**Comment by keirf** [comment]
HD disks with hole covered are usually reliable enough. What disk image type are you comparing in the hex editor?

**Comment by gilmod714** [comment]
i am writing an .hfe image ready-made found online-> type 07 , testing it on real MTX512 disk drive works ok, then reading back that same disk I created as .hfe also type07 ..then comparing it against the original .hfe image  .. some bytes are different ..

![compare](https://github.com/user-attachments/assets/53656ca6-32ef-4d1a-a6c5-26a88dfd3c05)

[disk-comparison.zip](https://github.com/user-attachments/files/17705598/disk-comparison.zip)

**Comment by keirf** [comment]
You can't hex-compare HFE image files. They are raw, containing lower-level info than just sector data, and it can vary across dumps etc. So, case closed!
