### ISSUE TITLE
Wiki BOM incorrect for F7 Lightning

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [keirf/Greaseweazle#51]
U1 should be
U1 | LQFP144 | STM32F730Z8T6
instead of 
U1 | LQFP64 | STM32F730R8

https://github.com/keirf/Greaseweazle/wiki/F7-Lightning-Assembly

**Comment by keirf** [comment]
Thanks will fix by Monday.

**Comment by keirf** [comment]
Fixed.

**Comment by UnKnoWn-Consortium** [comment]
@keirf It seems you have missed the footprint. It is still LQFP64 instead of LQFP144.

**Comment by keirf** [comment]
Fixed again! Thanks!
