### ISSUE TITLE
Greaseweazle Models page

### ISSUE THREAD

**Issue by solarmon** [keirf/Greaseweazle#53]
Hi Keir,

As requested, a ticket to remind you to update the Greaseweazle Models page!:

https://github.com/keirf/Greaseweazle/wiki/Greaseweazle-Models

to show the various models and differences.

Thank you.

**Comment by keirf** [comment]
Done

**Comment by andrewbird** [comment]
Aren't you missing a picture of `F7 Lightning Plus` from the gallery?

**Comment by keirf** [comment]
I haven't built one yet. Got the pcbs today!
