### ISSUE TITLE
Feature request: EDSK

### ISSUE THREAD

**Issue by SM7I** [keirf/greaseweazle#55]
Would love to see EDSK support to be able to read/write +3 / CPC disks. Would simplify life alot.

**Comment by staticmem** [comment]
I wrote a shell script to easily convert disks to different formats, visit this link:
https://www.microbee-mspp.org.au/public_repository/

Then navigate to "home/public/Projects/fio1_fio2_gw_scripts/fiox.sh" after completing the Google challenge.

It may also be run under Windows if "Gow" is installed.  Details are in the script.  Note "fio2" is my variation of Greaseweasel and "fio1" is an earlier Floppy design reader.  It needs some dependencies installed.

**Comment by d235j** [comment]
@staticmem could you you put your software/scripts (not large downloads) somewhere where it's not behind a CAPTCHA?

**Comment by staticmem** [comment]
> @staticmem could you you put your software/scripts (not large downloads) somewhere where it's not behind a CAPTCHA?

What's the problem with the CAPTCHA anyway?  Would you prefer it to go up on Facebook where you have to log in and have a Facebook account.

**Comment by SM7I** [comment]
External script is a nogo. The support must be in firmware.

**Comment by staticmem** [comment]
> External script is a nogo. The support must be in firmware.

It has nothing to do with Firmware, the firmware knows nothing about image formats except maybe SCP.  Once you have the SCP image it can be converted to whatever format you want using the appropriate software. SCP to EDSK conversion works and if you look at the script you can see how it works.

The link that was included before was broken but now working again.

**Comment by keirf** [comment]
The initial write support can be tested using this automated build:
https://nightly.link/keirf/Greaseweazle/actions/artifacts/43511871.zip

**Comment by staticmem** [comment]
Can I assume that the FW has not changed to make this happen and this EDSK support is handled in the Python scripts?

**Comment by keirf** [comment]
Yep

**Comment by staticmem** [comment]
Nice addition. :-)

**Comment by merlinkv** [comment]
Hello Keirf.

Yesterday I successfully connected a 3 "drive to the Greaseweazle and can read / write a standard 3" disk with no problem. But I agree with @ SM7I and would greatly appreciate if EDSK support for reading / writing CPC / ZX discs were integrated into future firmware.

Thank you very much for your great work.
