### ISSUE TITLE
Empty SCP from wiped disk results in a Python error

### ISSUE THREAD

**Issue by root42** [keirf/Greaseweazle#61]
Marcus provided me with a disk image from a wiped/empty disk (i.e. no flux) created by a real Supercard Pro. This leads to a Python error:

`** FATAL ERROR:
unpack requires a buffer of 4 bytes`

The disk image is attached, I was using v0.22.

[empty.scp.zip](https://github.com/keirf/Greaseweazle/files/5624939/empty.scp.zip)

**Comment by keirf** [comment]
Ah yes I can reproduce this. I think the parser is a bit broken. I'll fix it tomorrow. Thanks!
