### ISSUE TITLE
No error output after three ADF write retries

### ISSUE THREAD

**Issue by solarmon** [keirf/Greaseweazle#71]
Greaseweazle version v0.23

If _SIDE signal not working, an ADF read will not output an error after the third attempt - see example:

![image](https://user-images.githubusercontent.com/46369787/104843585-5bfb6080-58c3-11eb-8b87-fac0af5b090b.png)

It does output a critical error right at the end, but it should be erroring after each third failed attempt.

**Comment by keirf** [comment]
This is fixed for next release.
