### ISSUE TITLE
Graseweazle SCP format & GUI

### ISSUE THREAD

**Issue by merlinkv** [keirf/Greaseweazle#80]
Hello Keirf.

I'm owner of one SuperCard Pro that uses the original SCP format to read/write disk and create iages, but the SCP files created with Greaseweazle are incompatible with the SuperCard Pro.

Why?

Also the GUI can't run on Windows XP machine, all times I get: "Is not a valid Win32 application" ...

Any help will be much appreciated.

**Comment by keirf** [comment]
Incompatible how? Greaseweazle version? They should be compatible.

XP is not supported by greaseweazle tools. I recommend at least Win7.

**Comment by merlinkv** [comment]
SuperCard Pro can't read SCP files created with Greasewaezle.

SCPro software all times recognizes SCP files (Greaseweazle) as CP/M files.

**Comment by merlinkv** [comment]
I have tested two SCP files created by a friend with Greasewaezle F1 (I think). As my friend said, these images transfered again to real disks works fine.

But I can't use these images with SuperCard Pro.

**Comment by keirf** [comment]
Interesting. What do you want to do with them in supercard Pro? Does it matter they identify as cpm?

**Comment by merlinkv** [comment]
Well, I want to write these images to real disks (Amiga), but I can't do it because are identidied as CP/M files.

**Comment by keirf** [comment]
As with a lot of third party software, Greaseweazle doesn't bother setting the id header byte (that's the fourth byte). Supercard Pro seems to care about that byte a lot. If you know how you could try changing the fourth byte from hex value 80 to value 04. Value 04 means Amiga.

**Comment by merlinkv** [comment]
Yes, that's the problem. I have changed the fourth byte to 04 make an now I have an usable image with SuperCard Pro.

It's possible to change this in the Greasewazle firm/soft? or is a problem?

Anyway, thanks you very much.

**Comment by merlinkv** [comment]
Updated images (fourth byte to 04), can be usable with SCPro & WinUAE and can be written to real disk without issues.

**Comment by keirf** [comment]
I will add a syntax to allow the SCP ID byte to be specified. Something like `gw read my.scp::disktype=4` I expect.

**Comment by merlinkv** [comment]
Great! Thanks you very much.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
