### ISSUE TITLE
Save partial SCP file on Ctrl-C

### ISSUE THREAD

**Issue by philpem** [keirf/greaseweazle#91]
I occasionally image disks which are suffering from "sticky shed" (e.g. Wabash) or have physical damage. Currently, if you use Ctrl-C to abort Greaseweazle, it deletes the output file.

Would it be possible for Greaseweazle to save the partial output file instead?

This would allow the read process to be paused, the drive head cleaned, and the read restarted in a new image. At the end, all the images could be combined into one.

**Comment by keirf** [comment]
Good idea.
