### ISSUE TITLE
Newest hardware F7 v3 F7 Plus info

### ISSUE THREAD

**Issue by badass-boss** [keirf/Greaseweazle#94]
I can see there was some very recent update with new models introduced F7 v3 and F7 plus, however I can't see any hardware info or PCBs of them. Is this going to be published?? Please reply. Thanks in advance

**Comment by keirf** [comment]
F7 Plus is existing model by a third party. It has its own GitHub repository. Look up user aerobaticant on GitHub.

F7 v3 is awaiting final boards. It will be published in due course.

**Comment by keirf** [comment]
F7 Plus and F7 v3 design files are now linked in the Hardware Assembly section of the wiki.
