### ISSUE TITLE
V7 Lightning Plus misreads disks with TEC FB-502 drive

### ISSUE THREAD

**Issue by philpem** [keirf/Greaseweazle#96]
I've encountered an odd incompatibility between the V7 Lightning Plus and the TEC FB-502 disk drive. This is a fairly early Japanese-made 5.25in single-sided drive which is sometimes seen in BBC Micro external drive boxes.

This drive works fine on a BBC Micro -- I can format the disk with Acorn DFS, and it verifies fine. However, when I hook the drive up to Greaseweazle, the resulting SCP files are unreadable. Neither HxCFE nor disk-analyse can make any sense of them.

I've attached an image of the formatted disc for reference.
[fb502_formatted_bbc.zip](https://github.com/keirf/Greaseweazle/files/6253830/fb502_formatted_bbc.zip)

**Comment by keirf** [comment]
Try `gw pins 2 L` to toggle the density select pin, and then try reading.

**Comment by philpem** [comment]
Sadly that didn't help, the disk image is still garbage. Although the stream does look vaguely plausible in HxC.
![image](https://user-images.githubusercontent.com/845744/113516815-44538000-9574-11eb-86af-0dc6c6896ae7.png)
