### ISSUE TITLE
F7 Lightning Plus board SMD units system

### ISSUE THREAD

**Issue by Jujan** [keirf/Greaseweazle#99]
I am browsing parts list for F7 Lightning Plus and found no information about SMD units system used. Which one is used for the SMD? The imperial or metric?

**Comment by drdpj** [comment]
0603 imperial

**Comment by keirf** [comment]
We wouldn't be popular forcing people to solder 0603 metric!

**Comment by Jujan** [comment]
Thank you. Closing now.
